# Use the official Node.js image as the base image
FROM node:18

# Set the working directory inside the container to the root
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code, including index.js in the root
COPY . .
# Inject the credentials into /usr/src/app instead
ARG FIREBASE_CREDENTIALS
RUN echo "$FIREBASE_CREDENTIALS" > /usr/src/app/credentials.json

# Expose the port your app runs on
EXPOSE 3000

# Start the application using nodemon
CMD ["node", "index.js"]
